[package]
name = "inpoly"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/jreniel/inpoly-rust.git"
description = "Fast point-in-polygon testing using the crossing-number algorithm"

[dependencies]
ndarray = "0.16"
ndarray-stats = "0.6"
