[package]
name = "inpoly"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE.md"
repository = "https://github.com/jreniel/inpoly-rust.git"
description = "Rust rewrite of Darren Engwirda's inpoly-python"

[dependencies]
ndarray = "0.16"
ndarray-stats = "0.6"
